# Generated by Django 4.2.7 on 2023-11-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=10, verbose_name='Тикер')),
                ('key_word', models.CharField(default='', max_length=300, verbose_name='ключевые слова')),
            ],
            options={
                'verbose_name': 'Тикер',
                'verbose_name_plural': 'Тикеры',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_list', models.CharField(default='gazp, sber', max_length=100, verbose_name='Список наблюдения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователя',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='Заголовок')),
                ('source', models.CharField(default='', max_length=50, verbose_name='источник')),
                ('sentiment_label', models.IntegerField(default=0, verbose_name='лейбл')),
                ('sentiment_str', models.CharField(default='', max_length=15, verbose_name='сентимен-анализ')),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='уверенность анализа')),
                ('date_time', models.DateTimeField(null=True, verbose_name='дата новости')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ticker', verbose_name='Тикер')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_news', models.IntegerField(verbose_name='позитивные новости')),
                ('negative_news', models.IntegerField(verbose_name='негативные новости')),
                ('date_history', models.DateField(null=True, verbose_name='дата новости')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ticker', verbose_name='Тикер')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истоия',
                'ordering': ['-date_history'],
            },
        ),
    ]
